import Head from "next/head";
import { useRouter } from "next/router";
import { FormEvent, useEffect, useState } from "react";
import { useUserContext } from "../contexts/userContext";

export default function Home() {
  const router = useRouter();
  const { name, setName } = useUserContext();
  const [room, setRoom] = useState("");
  const handleSubmitForm = (e: FormEvent) => {
    e.preventDefault();
    if (!name || !room) {
      return;
    }
    localStorage.setItem("user", name);
    setTimeout(() => {
      router.push(`/room/${room}`);
    }, 1000);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>Olá posolkey</div>

      <div>
        <form onSubmit={(e) => handleSubmitForm(e)}>
          <label htmlFor="name">Digite seu nome</label>
          <input
            type="text"
            name="name"
            id="name"
            onChange={(e) => setName(e.target.value)}
          />
          <label htmlFor="room">Digite o ID da sala</label>
          <input
            type="text"
            name="room"
            id="room"
            onChange={(e) => setRoom(e.target.value)}
          />
          <input type="submit" value="Enviar" />
        </form>
      </div>
    </div>
  );
}
